language: go

go:
- 1.13.x

deploy:
  provider: releases
  api_key:
    # mbyczkowski's OAuth token
    secure: phWdB/u3MZyzo3EGj35PTQdOWagxmAqBxXbQWl/ROL7zYGdyV3ix2EYxElTHpJ6lEksVHRnq3vUyGn0FNBS1jDNU93HQZpC6GPvtGtHfPEWXEk9X2H4cKUsMMfhqihJoA/Fx/S1ExQyVj7JxjnFW2/36J12qlR+gGDM0MOVw08Y=
  file_glob: true
  file: bin/certstrap-*
  skip_cleanup: true
  draft: true
  on:
    repo: square/certstrap
    tags: true
    go: "1.13.x" # ensure that this matches one of the go versions specified at the top

script:
- "./integration_test"
